### ISSUE TITLE
Question: memoize-state (with/without reselect)?

### ISSUE THREAD

**Issue by suwarnoong** [theKashey/memoize-state#28]
Hi @theKashey,

I wanted to fix the unnecessary re-rendering issue on react native. I have tried [reselect](https://github.com/reduxjs/reselect) (selector with memoization), however it does not solve the re-rendering issue.

While searching around, I found this memoize-state. Interestingly, this solve the issue by wrapping this with mapStateToProps.

If you don't mind, could you help me to clear some of my doubts here:
1. If my objective is simply prevent unnecessary re-rendering in react, do you think memoize-state is enough for that without [reselect](https://github.com/reduxjs/reselect)?
2. In this case, do you recommend to wrap all the mapStateToProps with memoize-state? Or perhaps there are some exception case that I should not do for every mapStateToProps.

**Comment by theKashey** [comment]
It always depends on the task and why reselect is not working properly.
If your issue is driven by multiple instances of a Component (or a selector) - just wrapping would not work due to a _single cache line_ still being a problem.

Ways to fix:
- using a weak-map based [kashe](https://github.com/theKashey/kashe) - https://dev.to/thekashey/memoization-forget-me-bomb-34kh
- using a smart reselect, [redux-views](https://github.com/josepot/redux-views) - https://medium.com/@josepot/we-need-better-redux-selectors-457a1ed10732
- using a bit [more complex memoize-state](https://github.com/theKashey/beautiful-react-redux) configuration, to be more concrete - "mapStateToProps factory". __Try this one__ first - it might work out of the box.

**Comment by suwarnoong** [comment]
Thanks @theKashey
